//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Humica.Training.DB
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.SqlTypes;
    using System.Security.Permissions;
    using System.Security.Policy;

    public partial class ESSTrainingSchedule
    {
        [Key]
        [Column(Order = 0)]
        public string TrainNo { get; set; }
        [Key]
        [Column(Order = 1)]
        public int No { get; set; }
        public DateTime TrainDate { get; set; }
        public DateTime FromTime { get; set; }
        public DateTime ToTime { get; set; }
        public decimal Hour { get; set; }

    }
}
