//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Humica.Training.DB
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class TrainingRequestItem
    {
        [Key]
        [Column(Order = 0)]
        public int ID { get; set; }
        public int TrainID { get; set; }
        [Key]
        [Column(Order = 1)]
        public int LineItem { get; set; }
        [Key]
        [Column(Order = 2)]
        public string RequestCode { get; set; }
        public Nullable<System.DateTime> RequestDate { get; set; }
        public Nullable<int> Group { get; set; }
        public string Status { get; set; }
        public string Position { get; set; }
        public string Department { get; set; }
        public string TrainingType { get; set; }
        public string TrainingCourse { get; set; }
        public string TrainingCategory { get; set; }
        public string TrainerName { get; set; }
        public int NumOfEmpJoin { get; set; }
        public DateTime FromDate { get; set; }
        public DateTime ToDate { get; set; }
        public string Locations { get; set; }
        public string EmpCode { get; set; }
        public string EmpName { get; set; }
        public string RequesterName { get; set; }
        public string TrainNo { get; set; }
        public decimal HAmount { get; set; } 
    }
}
