//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Humica.Training.DB
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.SqlTypes;
    using System.Security.Permissions;

    public partial class TrainingRequestHeader
    {
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int ID { get; set; }
        public string TrainNo { get; set; }
        public string RequestCode { get; set; }
        public string RequesterName { get; set; }
        public string Status { get; set; }
        public DateTime? RequestDate { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string ChangedBy { get; set; }
        public Nullable<System.DateTime> ChangedOn { get; set; }
        public string Department { get; set; }
        public string TrainingCourse { get; set; }
        public string TrainingType { get; set; }
        public string TrainingCategory { get; set; }
        public string TrainerName { get; set; }
        public int NumOfEmpJoin { get; set; }
        public DateTime FromDate { get; set; }
        public DateTime ToDate { get; set; }
        public string Locations { get; set; }
        public string EmpCode { get; set; }
        public string EmpName { get; set; }
        public decimal LineItem { get; set; }
        public string Position { get; set; }
        public string Remark { get; set; }
        public string ApproverCode { get; set; }
        public string ApproverName { get; set; }
        public DateTime? ApprovedDate { get; set; }
        public string AttachFile { get; set; }
        public decimal Duration { get; set; }
        public DateTime? FromTime { get; set; }
        public DateTime? ToTime { get; set; }
        public decimal TrainingFee { get; set; }
        public string Purpose { get; set; }
        public string Scopes { get; set; }
        public string Branch { get; set; }
        public string DocType { get; set; }
        public string Expected { get; set; }
        public string DirComment { get; set; }
        public DateTime? SessDate { get; set; }
    }
}
